language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
services:
  - redis-server
before_install:
  - "cpanm --notest Dist::Zilla Pod::Elemental::Transformer::List Pod::Coverage::TrustPod"
install: "dzil authordeps | cpanm --notest && dzil listdeps | cpanm --notest"
script: "dzil test --release"
